async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let data=null;try{data=await res.json()}catch(_){data={}}if(!res.ok)throw new Error(data.detail||`HTTP ${res.status}`);return data}
function backendMediaToVideo(x){const d=+x.duration_seconds||5,ranges=x.editorial_ranges||[];return{id:`dbv${x.id}`,dbId:x.id,file:x.filename,label:(x.title||x.filename).replace(/\.[^.]+$/,''),duration:d,tags:x.tags||[],canon:!!x.canonical,safe:!!x.trailer_safe,spoiler:+x.spoiler_level||0,note:x.description||x.relative_path,in:0,out:d,url:x.stream_url||null,filmstripUrl:x.filmstrip_url||null,analysis:x.analysis||null,semanticProfile:x.semantic_profile||null,editorialRanges:ranges,favorite:ranges.some(r=>r.kind==='favorite'),rejected:ranges.some(r=>r.kind==='reject')}}
function inferAudioRole(x){const z=((x.title||'')+' '+x.relative_path+' '+(x.tags||[]).join(' ')).toLowerCase();if(/dialogue|dialog|speech|interview/.test(z))return'dialogue';if(/voice|voix|voiceover|vo_|narrat/.test(z))return'vo';if(/music|musique|bed|score/.test(z))return'music';if(/ambience|ambiance|roomtone|room tone|atmo|atmos/.test(z))return'ambience';return'sfx'}
function backendMediaToAudio(x){const d=+x.duration_seconds||2;return{id:`dba${x.id}`,dbId:x.id,file:x.filename,label:(x.title||x.filename).replace(/\.[^.]+$/,''),role:inferAudioRole(x),duration:d,tags:x.tags||[],note:x.description||x.relative_path,url:x.stream_url||null,peaks:null,loudness:x.audio_loudness||null}}
function renderBackendCanon(state){const canon=state.canon||{},locks=state.locks?.locks||[];const cards=[];locks.forEach(l=>cards.push(`<div class="card"><h3>${l.level||'LOCK'} · ${l.name||'zone'}</h3><p>${(+l.start).toFixed(2)}–${(+l.end).toFixed(2)} s · interdictions : ${(l.forbidden||[]).join(', ')||'toutes les opérations'}</p></div>`));const look=canon.visual?.look||[];cards.push(`<div class="card"><h3>Look canonique</h3><p>${look.length?look.join(' · '):'Aucune règle visuelle définie.'}</p></div>`);const motifs=canon.sound?.motifs||[];cards.push(`<div class="card"><h3>Son</h3><p>${motifs.length?motifs.join(' · '):'Aucun motif sonore défini.'}</p></div>`);$('#canonCards').innerHTML=cards.join('')}
function renderBackendVersions(state){const vs=state.versions||[];if(vs.length&&!activeVersion)activeVersion=vs[vs.length-1].version_label;$('#versionsCards').innerHTML=vs.length?vs.slice().reverse().map(v=>`<div class="card" style="${v.version_label===activeVersion?'border-color:#875a36':''}"><h3>${v.version_label} · ${v.edit_name}${v.version_label===activeVersion?' · ACTIVE':''}</h3><p>${v.kind} · ${v.parent_version_label?`parent ${v.parent_version_label}`:'version racine'} · ${v.created_at||''}</p><div class="ins-actions"><button class="btn" onclick="activeVersion='${v.version_label}';renderBackendVersions(backendState);toast('${v.version_label} sélectionnée')">Sélectionner</button></div></div>`).join(''):'<div class="card"><h3>Aucune version enregistrée</h3><p>Enregistre puis publie la timeline pour créer V001.</p></div>'}
function hydrateTimeline(doc){if(!doc)return;DURATION=+doc.duration_seconds||30;activeEditName=doc.edit_name||'teaser_30';tracks.splice(0,tracks.length,...(doc.tracks||[]));clips=(doc.clips||[]).map(c=>{const n={...c};if(typeof normalizeAudioClip==='function')normalizeAudioClip(n);if(c.mediaDbId){const m=media.find(x=>x.dbId===c.mediaDbId);if(m)n.mediaId=m.id}if(c.audioDbId){const a=audioAssets.find(x=>x.dbId===c.audioDbId);if(a)n.audioId=a.id}return n});if(typeof setStorylineStateFromDoc==='function')setStorylineStateFromDoc(doc);selectedClip=clips[0]?.id||null}
async function hydrateBackend(){if(!/^https?:$/.test(location.protocol)){return}try{const state=await api('/api/state');backendConnected=true;backendState=state;if(typeof hydrateEditorialState==='function')hydrateEditorialState(state);if((state.versions||[]).length&&!activeVersion)activeVersion=state.versions[state.versions.length-1].version_label;const p=state.project?.project||{};$('#projectName').textContent=p.name||state.canon?.project?.title||'PISTE Studio';$('#projectSubtitle').textContent=(state.canon?.project?.subtitle||'')+' · '+activeEditName;const vids=(state.media||[]).filter(x=>x.kind==='video').map(backendMediaToVideo),auds=(state.media||[]).filter(x=>x.kind==='audio').map(backendMediaToAudio);media.splice(0,media.length,...vids);audioAssets.splice(0,audioAssets.length,...auds);const hardLocks=(state.locks?.locks||[]).filter(l=>String(l.level||'').toUpperCase()==='HARD'&&(+l.start||0)===0);HARD_END=hardLocks.length?Math.max(...hardLocks.map(l=>+l.end||0)):0;hydrateTimeline(state.timeline);selectedMedia=media[0]?.id||null;selectedAudio=audioAssets[0]?.id||null;$('#backendStatus').textContent='BACKEND CONNECTÉ';$('#backendStatus').classList.remove('warn');$('#backendFoot').innerHTML=`MASTER_PROTECTED = TRUE<br>Backend local connecté<br>${state.tesseract?.ready?'Tesseract prêt':'Tesseract non prêt'}`;$('#hardLockLabel').textContent='LOCKS PROJET → Canon & Locks';renderBackendCanon(state);renderBackendVersions(state);renderMedia();renderTracks();setPlayhead(0);toast('Projet chargé depuis le backend')}catch(err){$('#backendStatus').textContent='BACKEND ERREUR';$('#backendFoot').innerHTML='Mode navigateur autonome<br>'+err.message;toast('Backend indisponible : '+err.message,true)}}
async function saveBackendTimeline(){if(!backendConnected){toast('Backend local non connecté',true);return false}const payload=typeof backendTimelinePayload==='function'?backendTimelinePayload():{edit_name:activeEditName,duration_seconds:DURATION,tracks,clips:clips.map(c=>{const n={...c};const m=c.mediaId&&getMedia(c.mediaId),a=c.audioId&&getAudio(c.audioId);if(m?.dbId)n.mediaDbId=m.dbId;if(a?.dbId)n.audioDbId=a.dbId;return n})};try{await api('/api/timeline',{method:'POST',body:JSON.stringify(payload)});toast('Timeline enregistrée côté backend');return true}catch(err){toast('Enregistrement refusé : '+err.message,true);return false}}
async function scanBackend(){if(!backendConnected){toast('Backend local non connecté',true);return}try{const r=await api('/api/scan',{method:'POST',body:'{}'});toast(`Scan : ${r.scan.inserted} ajouté(s), ${r.scan.updated} mis à jour`);await hydrateBackend()}catch(err){toast('Scan impossible : '+err.message,true)}}
async function publishVersion(){if(!backendConnected){toast('Backend local requis',true);return null}if(!(await saveBackendTimeline()))return null;try{const r=await api('/api/publish',{method:'POST',body:JSON.stringify({edit_name:activeEditName})});activeVersion=r.version;toast(`${r.version} créée depuis la timeline`);await hydrateBackend();return r.version}catch(err){toast('Publication refusée : '+err.message,true);return null}}
async function prepareTesseract(){if(!backendConnected){toast('Backend local requis pour Tesseract',true);return}try{if(!activeVersion){activeVersion=await publishVersion();if(!activeVersion)return}const st=await api('/api/tesseract/status');if(!st.ready){toast((st.message||'Tesseract non prêt')+` · ${activeVersion} reste publiée`,true);return}toast(`Bootstrap ${activeVersion}…`);await api(`/api/tesseract/${activeVersion}/bootstrap`,{method:'POST',body:JSON.stringify({edit_name:activeEditName,execute:true})});toast(`Authoring ${activeVersion}…`);const r=await api(`/api/tesseract/${activeVersion}/author`,{method:'POST',body:JSON.stringify({edit_name:activeEditName,execute:true})});toast(`${activeVersion} authorée · ${(r.manifest?.layers||[]).length} vidéo · ${(r.manifest?.audio_layers||[]).length} audio`);await hydrateBackend()}catch(err){toast('Tesseract : '+err.message,true)}}
async function previewTesseract(){if(!activeVersion){toast('Publie d’abord une version',true);return}try{const r=await api(`/api/tesseract/${activeVersion}/preview`,{method:'POST',body:JSON.stringify({edit_name:activeEditName,time_seconds:Math.min(playhead,DURATION-.01)})});toast(`Preview créée : ${r.path}`)}catch(err){toast('Preview : '+err.message,true)}}
async function exportTesseract(forceAudio=false){
  if(!activeVersion){toast('Publie d’abord une version',true);return}
  try{
    if(!forceAudio){
      let audioStatus=null;
      try{audioStatus=await api(`/api/audio/master/status?edit_name=${encodeURIComponent(activeEditName)}`)}
      catch(err){audioStatus={status:'MISSING',can_export:true,message:'Master Check indisponible : '+err.message,reasons:['Contrôle audio non vérifié.']}}
      if(audioStatus?.status!=='PASS'&&typeof openAudioExportAdvisory==='function'){openAudioExportAdvisory(audioStatus);return}
    }
    const r=await api(`/api/tesseract/${activeVersion}/export`,{method:'POST',body:JSON.stringify({edit_name:activeEditName,resolution:'1080p',fps:24,format:'mp4'})});
    const audio=r.audio_delivery||{};
    const suffix=audio.status?` · Audio ${audio.status}`:'';
    toast(`Export créé : ${r.path}${suffix}`,['WARN','STALE','MISSING'].includes(audio.status))
  }catch(err){toast('Export : '+err.message,true)}
}

function switchView(v){$$('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));}
$$('.nav-tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('.libtab').forEach(b=>b.onclick=()=>{libraryMode=b.dataset.lib;renderMedia();if(libraryMode==='audio')renderAudioInspector();else renderMediaInspector()});$('#mediaSearch').oninput=renderMedia;$('#snap').onchange=()=>{renderInspector();toast(`Snap ${snapValue()} s`)};
$('#scanBtn').onclick=scanBackend;if($('#analyzeMediaBtn'))$('#analyzeMediaBtn').onclick=()=>typeof analyzeMediaCatalog==='function'&&analyzeMediaCatalog();$('#saveBackendBtn').onclick=saveBackendTimeline;$('#bindBtn').onclick=()=>{window.__bindTarget=null;$('#multiFileInput').value='';$('#multiFileInput').click()};$('#bindAudioBtn').onclick=()=>{$('#multiAudioInput').value='';$('#multiAudioInput').click()};
$('#multiFileInput').onchange=e=>{let matched=0;[...e.target.files].forEach(file=>{const m=media.find(x=>x.file.toLowerCase()===file.name.toLowerCase());if(m){bindFileToMedia(m,file);matched++}});renderMedia();renderInspector();toast(matched?`${matched} rush(es) associé(s) par nom`:'Aucun nom de fichier ne correspond aux rushes',!matched)};
$('#singleFileInput').onchange=e=>{const f=e.target.files[0],m=getMedia(window.__bindTarget);if(!f||!m)return;bindFileToMedia(m,f);renderMedia();renderInspector();previewMedia(m.id);toast(`${m.file} associé à ${f.name}`)};
$('#multiAudioInput').onchange=async e=>{let matched=0,created=0;for(const file of [...e.target.files]){let a=audioAssets.find(x=>x.file.toLowerCase()===file.name.toLowerCase());if(!a){const id='au_'+Date.now()+'_'+created;a={id,file:file.name,label:file.name.replace(/\.[^.]+$/,''),role:'sfx',duration:2,tags:['import'],note:'Audio local importé.',url:null,peaks:null};audioAssets.push(a);created++}else matched++;await bindAudioFile(a,file)}libraryMode='audio';renderMedia();renderAudioInspector();renderTracks();toast(`${matched+created} source(s) audio importée(s)`)};
$('#singleAudioInput').onchange=async e=>{const f=e.target.files[0],a=getAudio(window.__bindAudioTarget);if(!f||!a)return;await bindAudioFile(a,f);libraryMode='audio';renderMedia();renderAudioInspector();renderTracks();toast(`${a.file} associé à ${f.name}`)};
window.addEventListener('resize',()=>requestAnimationFrame(drawAllWaveforms));
window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.code==='Space'){e.preventDefault();togglePlay()}if(e.key==='ArrowLeft')step(-snapValue());if(e.key==='ArrowRight')step(snapValue())});
initRuler();renderMedia();renderTracks();setPlayhead(0);hydrateBackend();